name: jonction-tree-canopy
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - -e .
  - setuptools
  - wheel
  - click
  - flake8
  - flake8-isort>=4
  - python-dotenv>=0.5.1
  - python=3
  - detectree>=0.4.1
  - geopandas
  - laspy
  - lastools
  - laszip  
  - rasterio
  - shapely
